In [1]:
import pandas as pd
import numpy as np

In [2]:
#dataset of pixels as columns and number of rows as samples numbers,-(10),+(11),*(12) as labels
df_train=pd.read_csv('trainingdata_final.csv', index_col=False)
df_train.head()

C:\Users\KUNAL MEHTA\AppData\Roaming\Python\Python38\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (784) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


0  1  2  3  4  5  6  7  8   9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  14  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   

   783  784  
0    0    +  
1    0    +  
2    0    +  
3    0    +  
4    0    +  

[5 rows x 785 columns]

In [3]:
labels=df_train['784']

In [4]:
df_train.drop(df_train.columns[[784]], axis=1, inplace=True)
df_train.head()

0  1  2  3  4  5  6  7  8   9  ...  774  775  776  777  778  779  780  781  \
0  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  14  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   

   782  783  
0    0    0  
1    0    0  
2    0    0  
3    0    0  
4    0    0  

[5 rows x 784 columns]

In [5]:
np.random.seed(1212)
import keras
from keras.models import Model
from keras.layers import *
from keras import optimizers
from keras.layers import Input,Dense
from keras.models import Sequential
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils

In [6]:
# labels=np.array(labels)

In [7]:
labels

0         +
1         +
2         +
3         +
4         +
         ..
113346    ^
113347    ^
113348    ^
113349    ^
113350    ^
Name: 784, Length: 113351, dtype: object

In [8]:
['+',
 '-',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '=',
 'div',
 'log',
 'mul',
 '^']

['+',
 '-',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '=',
 'div',
 'log',
 'mul',
 '^']

In [9]:
dictonary={'div':'10','+':'11','-':"12",'mul':'13','^':'14','log':"15", '=':'16'}

In [10]:
def func(x):
    if x in dictonary.keys():
        return int(dictonary[x])
    else:
        return int(x)

In [11]:
labels=labels.apply(func)

In [12]:
from keras.utils.np_utils import to_categorical
cat=to_categorical(labels, num_classes=17)

In [13]:
cat.shape

(113351, 17)

In [14]:
df_train.head()

0  1  2  3  4  5  6  7  8   9  ...  774  775  776  777  778  779  780  781  \
0  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  14  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0   

   782  783  
0    0    0  
1    0    0  
2    0    0  
3    0    0  
4    0    0  

[5 rows x 784 columns]

In [15]:
l=[]
for i in range(len(df_train)):
    l.append(np.array(df_train[i:i+1]).reshape(28,28,1))

In [16]:
import pickle

# pickle train x data

In [17]:
with open("trainingdata_array",'wb') as fi:
    pickle.dump(np.array(l), fi)

# pickle train labels(y) data

In [18]:
with open("labels_array",'wb') as fi:
    pickle.dump(cat, fi)

In [19]:
np.random.seed(7)

In [20]:
model=Sequential()
model.add(Conv2D(30, (5,5), input_shape=(28,28,1), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(15, (3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128, activation="relu"))
model.add(Dense(50, activation="relu"))
model.add(Dense(17, activation="softmax"))

In [21]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
cat.shape

(113351, 17)

In [23]:
np.array(l).shape

(113351, 28, 28, 1)

In [24]:
model.fit(np.array(l), cat, shuffle=True, epochs=10)

Epoch 1/10
3543/3543 [==============================] - 38s 11ms/step - loss: 1.0289 - accuracy: 0.78350s - loss: 1.0324 - accura
Epoch 2/10
3543/3543 [==============================] - 38s 11ms/step - loss: 0.1814 - accuracy: 0.9459
Epoch 3/10
3543/3543 [==============================] - 35s 10ms/step - loss: 0.1294 - accuracy: 0.9602
Epoch 4/10
3543/3543 [==============================] - 36s 10ms/step - loss: 0.1120 - accuracy: 0.9656
Epoch 5/10
3543/3543 [==============================] - 35s 10ms/step - loss: 0.0990 - accuracy: 0.9688
Epoch 6/10
3543/3543 [==============================] - 35s 10ms/step - loss: 0.0969 - accuracy: 0.9691
Epoch 7/10
3543/3543 [==============================] - 35s 10ms/step - loss: 0.0896 - accuracy: 0.9724
Epoch 8/10
3543/3543 [==============================] - 36s 10ms/step - loss: 0.0902 - accuracy: 0.9717
Epoch 9/10
3543/3543 [==============================] - 37s 11ms/step - loss: 0.0822 - accuracy: 0.9740
Epoch 10/10
3543/3543 [===============

In [25]:
pred=model.predict_classes(np.array(l))

C:\Users\KUNAL MEHTA\anaconda3\envs\datascience\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [26]:
pred

array([11, 11, 11, ..., 14, 14, 14], dtype=int64)

In [27]:
np.array(labels)

array([11, 11, 11, ..., 14, 14, 14], dtype=int64)

In [28]:
loss, accuracy=model.evaluate(np.array(l), cat, verbose=0)

In [29]:
print(f"loss:{loss}\n accuracy:{accuracy}")

loss:0.051097847521305084
 accuracy:0.9822497963905334


In [30]:
model.save("model_handwritten")

INFO:tensorflow:Assets written to: model_handwritten\assets


In [31]:
from tensorflow import keras
m=keras.models.load_model('model_handwritten')

In [32]:
m.predict_classes(np.array(l))

C:\Users\KUNAL MEHTA\anaconda3\envs\datascience\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([11, 11, 11, ..., 14, 14, 14], dtype=int64)

In [33]:
np.array(l).shape

(113351, 28, 28, 1)